x = [1, 1, 1, 0]; 
X_fft = fft(x);
N=length(x);
disp('FFT of the sequence:');
disp(X_fft);
figure;
subplot(2,1,1);
stem((0:N-1), abs(X_fft), 'b');
title('Magnitude of FFT');
xlabel('k');
ylabel('Magnitude');
disp('magnitude response');
disp(abs(X_fft));
phase_radians = angle(X_fft);
phase_degrees = rad2deg(phase_radians);
subplot(2,1,2);
stem((0:N-1), phase_degrees, 'r');
title('Phase of FFT');
xlabel('k');
ylabel('Phase (radians)');
disp('phase response');
disp(phase_degrees);
